spring:
  application:
    name: equipment-failure-prediction

  datasource:
    url: jdbc:postgresql://localhost:5433/equipment_failure_db
    username: suyog
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

jwt:
  secret: 5nQ4x8P2mL9vA7sD1kH6jF3wR8yT0uB4cE5gN2pZ7qX9rL6mV1aC8dF4hJ7sK2
  expiration: 86400000

ml:
  service:
    url: http://localhost:8000